version: "3"

services:
  node:
    build: ./app
    working_dir: /app
    command: [/bin/bash, ./command.sh]
    expose:
      - "3000"
      - "3001"
  nginx:
    build: ./nginx
    working_dir: /nginx
    command: [/bin/bash, ./command.sh]
    ports:
      - "443:443"
      - "80:80"