version: "3"

services:
  node:
    build: ./app
    working_dir: /app
    volumes:
      - ./app:/app
    command: [/bin/bash, ./command.sh]
    ports:
      - "3000:3000"
      - "3001:3001"
  nginx:
    build: ./nginx
    ports:
      - "80:80"